//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkFlowProject.Models.DataBaseModel
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Leaf
    {
        public int LeaveId { get; set; }
        public Nullable<int> UserId { get; set; }
        [Required(ErrorMessage ="Leave Period is required")]
       [DataType(DataType.PostalCode)]
        public string LeavePeriod { get; set; }
        [Required(ErrorMessage = "Leave Reason is required")]
        public string Reason { get; set; }
        public Nullable<bool> Status { get; set; }
    
        public virtual User User { get; set; }
    }
}
