//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkFlowProject.Models.DataBaseModel
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Meeting
    {
        public int MeetingId { get; set; }
        [Required(ErrorMessage ="Please Select Topic")]
        public Nullable<int> TopicId { get; set; }
        public Nullable<int> UserId { get; set; }
        public string MeetingPoints { get; set; }
        public string MeetingTime { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<bool> IsViewd { get; set; }
        public virtual Topic Topic { get; set; }
        public virtual User User { get; set; }
    }
}
