//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkFlowProject.Models.DataBaseModel
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Web;

    public partial class Paper
    {
        public int PaperId { get; set; }
        public Nullable<int> UserId { get; set; }
        [DisplayName("Class Standard")]
        [Required(ErrorMessage ="Class Standard is required")]
        public string PaperStandard { get; set; }

        [DisplayName("Paper Subject")]
        [Required(ErrorMessage = "paper subjectis required")]

        public string PaperSubject { get; set; }
       
        public Nullable<bool> PaperStatus { get; set; }
    
        public virtual User User { get; set; }

        [DisplayName("Upload File")]
        public string FilePath { get; set; }

        [NotMapped]
        [Required(ErrorMessage = "Please upload File")]
        public HttpPostedFileBase fileUpload { get; set; }
    }
}
