//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkFlowProject.Models.DataBaseModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class PostComment
    {
        public int CommentId { get; set; }
        public Nullable<int> PostId { get; set; }
        public Nullable<int> UserId { get; set; }
        public string CommentTime { get; set; }
        public string CommentContent { get; set; }
        public Nullable<bool> Status { get; set; }
        public string UserFullName { get; set; }
    
        public virtual Post Post { get; set; }
        public virtual User User { get; set; }
    }
}
