//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkFlowProject.Models.DataBaseModel
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Web;

    public partial class Project
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Project()
        {
            this.ProjectTasks = new HashSet<ProjectTask>();
        }
    
        public int ProjectId { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<int> UserId { get; set; }
        public string CreatedDate { get; set; }
       // [Required(ErrorMessage = "Due date is required")]
        public string DueDate { get; set; }

       // [Required(ErrorMessage ="Project title is required")]
        public string ProjectTitle { get; set; }
        public string Description { get; set; }
        [DisplayName("Upload File")]
       // [Required(ErrorMessage = "Please upload project file")]
        public string FilePath { get; set; }

        [NotMapped]
       // [Required(ErrorMessage = "Please upload project file")]
        public HttpPostedFileBase fileUpload { get; set; }
        public Nullable<bool> Status { get; set; }
    
        public virtual User User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProjectTask> ProjectTasks { get; set; }
    }
}
