//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkFlowProject.Models.DataBaseModel
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class ProjectTask
    {
        public int TaskId { get; set; }
        public Nullable<int> ProjectId { get; set; }
        [Required(ErrorMessage ="Task Title is required.")]
        public string TaskTitle { get; set; }
        public string Description { get; set; }
        public string CreatedDate { get; set; }
        public string DueDate { get; set; }
        public Nullable<int> UserId { get; set; }
        public string AssignedBy { get; set; }
        public Nullable<bool> Status { get; set; }
    
        public virtual Project Project { get; set; }
        public virtual User User { get; set; }
    }
}
